[blueprint]
docs_server = '0.0.0.0:2332'
docs_domain = ''
entrypoints = [
    'blueprints.app:*',
]

[golang]
codegen_output = 'golang'
upstream = 'http://localhost:2333'
module = ''

[typescript]
codegen_output = 'typescript'
upstream = 'http://localhost:2333'
base_url = '"http://localhost:2333"'
